# Generated by Django 5.2.8 on 2025-11-19 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('url', models.URLField()),
                ('event_types', models.JSONField(default=list)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'webhook_config',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('status_code', models.IntegerField(null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('response_time', models.FloatField(null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='webhook.webhookconfig')),
            ],
            options={
                'db_table': 'webhook_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
