# Generated by Django 5.2.8 on 2025-11-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'product_product',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sku'], name='product_pro_sku_34f508_idx'), models.Index(fields=['name'], name='product_pro_name_b60cd1_idx'), models.Index(fields=['is_active'], name='product_pro_is_acti_9d034c_idx')],
            },
        ),
    ]
