# Generated by Django 5.2.8 on 2025-11-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productproduct',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
